version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=habr_pages
    volumes:
      - ./../db/database/:/var/lib/postgresql/data/
      - ./../db/scripts/init-habr-db.sql:/docker-entrypoint-initdb.d/init-habr-db.sql
      - ./../db/scripts/init-habr-db-json.sql:/docker-entrypoint-initdb.d/init-habr-db-json.sql
    ports:
      - 5431:5432

  parser:
    env_file:
      - .env
    build:
      context: ./../
      dockerfile: ./build/Dockerfile
    restart: on-failure
    depends_on:
      - db
